spring:
  application.name: blog-app
  datasource:
    username: blogapp
    url: jdbc:postgresql://localhost:5432/blogdb
    password: blogapp
    driver-class-name: org.postgresql.Driver
  profiles:
    active: development
  flyway:
    url: ${spring.datasource.url}
    user: blogapp
    password: blogapp
    schemas: blog_app